# Theme
remote_theme: 'epidrome/cover-card'

# Title and tag line
title: 'Khaeef sagt den Kampf an!'
description: 'Schluss mit lustig jetzt wird gef*ckt'

# Images
avatar: 'avatar.jpg'
background: 'background.jpg'
favicon: 'favicon.ico'

# Online profiles
#facebook: ''
#twitter: ''
#linkedin: ''
instagram: 'https://www.instagram.com/yonkha/'
#pinterest: ''
#youtube: ''
#github: ''
#codepen: ''
#steam: ''
#soundcloud: ''
#lastfm: ''
#stack-overflow: ''
#reddit: ''
#medium:  ''
#tumblr: ''
#weibo: ''
#vk: ''
#blog_url: ''
email: 'khaeef@yonas.fun'
#messenger: ''

# Advanced settings
plugins:
  - jekyll-remote-theme
